version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
    - "27017:27017"
  service-a:
    build: ./service-a
    ports:
      - "3000:3000"
  service-b:
    build: ./service-b
    ports:
      - "3001:3001"
